=============
dnd_encounter
=============

use this tool to populate a pdf combat tracker sheet with monster data

syntax example:
dnd-encounter Troll Aboleth 'Young Adult Dragon'

credits for the pdf go to:
Neskatomon over at Reddit.
https://www.reddit.com/r/DnD/comments/2d0y02/5th_edition_combat_tracker/
